# Generated by Django 5.0.4 on 2024-05-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phananh',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phananh',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='phananh',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='phananh',
            name='noiDung',
            field=models.TextField(),
        ),
    ]
