# Generated by Django 4.2.13 on 2024-05-26 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_canho_usermembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canho',
            name='userMembers',
            field=models.ManyToManyField(null=True, related_name='thanh_vien_can_ho', to=settings.AUTH_USER_MODEL),
        ),
    ]
