# Generated by Django 5.0.4 on 2024-05-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_phananh_active_phananh_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phananh',
            name='loaiPhanAnh',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
