# Generated by Django 5.0.4 on 2024-06-08 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_canho_usermembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='dichVu',
            field=models.ManyToManyField(blank=True, related_name='hoa_don', to='apartment.dichvu'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don', to=settings.AUTH_USER_MODEL),
        ),
    ]
