# Generated by Django 5.0.4 on 2024-05-14 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_hanghoa_status_alter_hanghoa_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhoikhaosat',
            name='phieukhaosat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi_khao_sat', to='apartment.phieukhaosat'),
        ),
        migrations.AlterField(
            model_name='dapankhaosat',
            name='cauhoikhaosat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dap_an_khao_sat', to='apartment.cauhoikhaosat'),
        ),
        migrations.AlterField(
            model_name='dapankhaosat',
            name='phieukhaosat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dap_an_khao_sat', to='apartment.phieukhaosat'),
        ),
        migrations.AlterField(
            model_name='phieukhaosat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phieu_khao_sat', to=settings.AUTH_USER_MODEL),
        ),
    ]
