# Generated by Django 5.0.4 on 2024-05-15 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_alter_cauhoikhaosat_phieukhaosat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don', to=settings.AUTH_USER_MODEL),
        ),
    ]
