# Generated by Django 5.0.4 on 2024-06-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_alter_hoadon_dichvu_alter_hoadon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
