# Generated by Django 5.0.4 on 2024-05-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_alter_hoadon_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoadon',
            name='dichVu',
        ),
        migrations.AddField(
            model_name='hoadon',
            name='dichVu',
            field=models.ManyToManyField(to='apartment.dichvu'),
        ),
    ]
