# Generated by Django 5.0.4 on 2024-05-06 05:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_rename_loaiphananh_phananh_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phananh',
            name='noiDung',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
