# Generated by Django 5.0.4 on 2024-05-06 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_alter_phananh_noidung'),
    ]

    operations = [
        migrations.AddField(
            model_name='phananh',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
