# Generated by Django 5.0.4 on 2024-05-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_remove_hoadon_dichvu_hoadon_dichvu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='dichVu',
            field=models.ManyToManyField(related_name='hoa_don', to='apartment.dichvu'),
        ),
    ]
