# Generated by Django 5.0.4 on 2024-05-15 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_alter_hoadon_dichvu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tudodientu',
            name='user',
        ),
        migrations.AddField(
            model_name='tudodientu',
            name='canho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.canho'),
        ),
    ]
