# Generated by Django 5.0.4 on 2024-05-15 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_alter_hanghoa_tudo_alter_tudodientu_canho_cudan'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiThan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('ten', models.CharField(max_length=100)),
                ('cmnd', models.CharField(max_length=20, unique=True)),
                ('sdt', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_than', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TheGiuXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('nguoithan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='the_giu_xe', to='apartment.nguoithan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CuDan',
        ),
    ]
