# Generated by Django 5.0.4 on 2024-05-06 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_phieukhaosat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tudodientu',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
