# Generated by Django 5.0.4 on 2024-05-15 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0010_rename_cmnd_nguoithan_cccd_rename_ten_nguoithan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopdong',
            name='user',
        ),
        migrations.AddField(
            model_name='hopdong',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hop_dong', to=settings.AUTH_USER_MODEL),
        ),
    ]
