# Generated by Django 5.0.4 on 2024-05-16 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0011_remove_hopdong_user_hopdong_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dichvu',
            name='users',
        ),
    ]
