# Generated by Django 5.0.4 on 2024-05-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0012_canho_hopdong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoadon',
            old_name='dichvu_hoadon',
            new_name='dichVu',
        ),
        migrations.RenameField(
            model_name='hopdong',
            old_name='hopdong_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='phieukhaosat',
            old_name='pks_user',
            new_name='user',
        ),
    ]
