# Generated by Django 5.0.4 on 2024-05-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0012_remove_dichvu_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoithan',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('pass', 'Đăng ký thành công')], default='pending', max_length=10),
        ),
    ]
