# Generated by Django 5.0.4 on 2024-05-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0013_rename_dichvu_hoadon_hoadon_dichvu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanghoa',
            name='image',
            field=models.ImageField(null=True, upload_to='HangHoa/%Y/%m'),
        ),
        migrations.AddField(
            model_name='phananh',
            name='image',
            field=models.ImageField(null=True, upload_to='PhanAnh/%Y/%m'),
        ),
        migrations.AddField(
            model_name='phieukhaosat',
            name='image',
            field=models.ImageField(null=True, upload_to='PhieuKhaoSat/%Y/%m'),
        ),
    ]
