# Generated by Django 5.0.4 on 2024-05-16 07:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0013_nguoithan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'quản trị viên'), ('resident', 'cư dân')], default='resident', max_length=20),
        ),
        migrations.AlterField(
            model_name='dapankhaosat',
            name='dapAn',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
