# Generated by Django 5.0.4 on 2024-05-07 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0015_user_avatar_alter_hanghoa_image_alter_phananh_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dichvu',
            name='user',
        ),
        migrations.AddField(
            model_name='dichvu',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
