# Generated by Django 5.0.4 on 2024-05-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0016_remove_dichvu_user_dichvu_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phieukhaosat',
            name='image',
        ),
        migrations.RemoveField(
            model_name='phieukhaosat',
            name='user',
        ),
    ]
