# Generated by Django 5.0.4 on 2024-05-07 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0017_remove_phieukhaosat_image_remove_phieukhaosat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieukhaosat',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
