# Generated by Django 5.0.4 on 2024-05-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0019_rename_name_phieukhaosat_tieude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phieukhaosat',
            old_name='tieuDe',
            new_name='name',
        ),
    ]
