# Generated by Django 5.0.4 on 2024-05-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0020_rename_tieude_phieukhaosat_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phieukhaosat',
            old_name='name',
            new_name='tieuDe',
        ),
    ]
