# Generated by Django 5.0.4 on 2024-05-07 07:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0021_rename_name_phieukhaosat_tieude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='payment_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
